name: Build & Release

env:
  GH_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:

  exe:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: npm ci

      - name: Release
        if: contains(github.ref, 'main')
        run: npm run dist:windows -- --publish always
        
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist\teams-for-linux Setup 2.0.10.exe
